/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.taikhoanDAO;
import Models.taikhoan;
import servicesANDvalidate.validate;
import servicesANDvalidate.validateEmail;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Dangnhap extends javax.swing.JFrame {
     private javax.swing.JDialog registerDialog;
    /**
     * Creates new form Dangnhap
     */
    public Dangnhap() {
        initComponents();
        initCustomComponents();
    }
    private void initCustomComponents() {
        // Đặt form ở giữa màn hình
        setLocationRelativeTo(null);
        // Thiết lập mật khẩu ẩn
        txtMk.setEchoChar('*');
        txtPass.setEchoChar('*');
        
        // Thêm real-time validation
        addRealTimeValidation();
    }
    private void updatePasswordValidationLogin() {
        String password = new String(txtMk.getPassword());
        validateEmail.validatePasswordSimple(password, lbbl1, lbbl2, lbbl3);
    }

    private void updatePasswordValidationRegister() {
        String password = new String(txtPass.getPassword());
        validateEmail.validatePasswordSimple(password, lbbl6, lbbl4, lbbl5);
    }

    private void addRealTimeValidation() {
        // Đăng nhập - Password
        txtMk.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { 
                updatePasswordValidationLogin(); 
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { 
                updatePasswordValidationLogin(); 
            }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { 
                updatePasswordValidationLogin(); 
            }
        });

        // Đăng ký - Password
        txtPass.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { 
                updatePasswordValidationRegister(); 
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { 
                updatePasswordValidationRegister(); 
            }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { 
                updatePasswordValidationRegister(); 
            }
        });
    }
    private void createRegisterDialog() {
        registerDialog = new javax.swing.JDialog(this, "Đăng ký tài khoản", true);
        registerDialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        
        // Thêm panel đăng ký vào dialog
        registerDialog.getContentPane().add(jPanel1);
        
        // Thiết lập kích thước dialog
        registerDialog.pack();
        registerDialog.setLocationRelativeTo(this);
        registerDialog.setResizable(false);
    }
    
    private void showRegisterDialog() {
        
        if (registerDialog == null) {
            createRegisterDialog();
        }
        
        // Clear các field đăng ký
        txtHoten.setText("");
        txtTDN.setText("");
        txtSdt.setText("");
        txtPass.setText("");
        cbRole.setSelectedIndex(0);
        
        // Reset màu các label
        lbbl6.setForeground(Color.BLACK);
        lbbl4.setForeground(Color.BLACK);
        lbbl5.setForeground(Color.BLACK);
        
        // Hiển thị dialog
        registerDialog.setVisible(true);
    }
    
    private void closeRegisterDialog() {
        if (registerDialog != null) {
            registerDialog.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTDN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbbl4 = new javax.swing.JLabel();
        lbbl5 = new javax.swing.JLabel();
        lbbl6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        btnDK = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lbDN = new javax.swing.JLabel();
        cbHT = new javax.swing.JCheckBox();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbbl1 = new javax.swing.JLabel();
        btnDN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbDK = new javax.swing.JLabel();
        lbbl2 = new javax.swing.JLabel();
        lbbl3 = new javax.swing.JLabel();
        cbht = new javax.swing.JCheckBox();
        txtMk = new javax.swing.JPasswordField();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ĐĂNG KÝ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Mật khẩu");

        lbbl4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbbl4.setText("Mật khẩu chứa kí tự viết hoa");

        lbbl5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbbl5.setText("Mật khẩu chứa ít nhất 6 kí tự ");

        lbbl6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbbl6.setText("Mật khẩu chứa ít nhất 1 số");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Số điện thoại");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Email");

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên bán hàng", "Nhân viên kho", " ", " " }));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Role");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Họ và tên");

        btnDK.setText("Đăng ký");
        btnDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Đã có tài khoản?");

        lbDN.setForeground(new java.awt.Color(0, 204, 204));
        lbDN.setText("Đăng nhập ngay");
        lbDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDNMouseClicked(evt);
            }
        });

        cbHT.setText("Hiển thị");
        cbHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoten)
                                    .addComponent(txtTDN)
                                    .addComponent(txtSdt)
                                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbbl6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbbl5))
                                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(307, 307, 307))))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDK)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDN, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbHT)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbHT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbbl6)
                .addGap(8, 8, 8)
                .addComponent(lbbl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbbl5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDK)
                    .addComponent(jLabel13)
                    .addComponent(lbDN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Email");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");

        lbbl1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbbl1.setText("Mật khẩu chứa ít nhất 1 số");

        btnDN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDN.setText("Đăng nhập");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Nhân viên mới ?");

        lbDK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbDK.setForeground(new java.awt.Color(0, 153, 255));
        lbDK.setText("Đăng ký tại đây");
        lbDK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDKMouseClicked(evt);
            }
        });

        lbbl2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbbl2.setText("Mật khẩu chứa kí tự viết hoa");

        lbbl3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbbl3.setText("Mật khẩu chứa ít nhất 6 kí tự ");

        cbht.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbht.setText("Hiển thị");
        cbht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbbl3))
                                .addGap(61, 61, 61)
                                .addComponent(cbht))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addComponent(txtDN, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 38, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDK)))
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbht)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbbl1)
                        .addGap(9, 9, 9)))
                .addComponent(lbbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbbl3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDN)
                    .addComponent(jLabel4)
                    .addComponent(lbDK))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
         String email = txtDN.getText();
        String password = new String(txtMk.getPassword());
        
        // Validate email
        String emailCheck = validateEmail.checkEmail(email);
        if (!emailCheck.equals("OK")) {
            JOptionPane.showMessageDialog(this,"Lỗi email: ");
            txtDN.requestFocus();
            return;
        }
        
        // Kiểm tra password có đạt tất cả yêu cầu không
        if (!validateEmail.isPasswordAllValid(password)) {
            JOptionPane.showMessageDialog(this,"Mật khẩu chưa đủ mạnh!");
            txtMk.requestFocus();
            return;
        }
        
        try {
            // Kiểm tra đăng nhập
            taikhoanDAO dao = new taikhoanDAO();
            if (dao.checkLogin(email, password)) {
            // Lấy thông tin user
            
                taikhoan currentUser = dao.getTaiKhoanByEmail(email);
                JOptionPane.showMessageDialog(this,"Đăng nhập thành công!");
                // Đóng form đăng nhập                
                mainmenu mainForm = new mainmenu();
                mainForm.setCurrentUser(currentUser); // Cần thêm phương thức này trong mainmenu
                mainForm.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,"Sai email hoặc mật khẩu!");
                txtMk.setText("");
                txtMk.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Lỗi kết nối: " + e.getMessage(), 
                "Lỗi hệ thống", 
                JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnDNActionPerformed

    private void lbDKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDKMouseClicked
        // TODO add your handling code here:
        showRegisterDialog();
    }//GEN-LAST:event_lbDKMouseClicked

    private void btnDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKActionPerformed
        // TODO add your handling code here:
        String email = txtTDN.getText();
        String password = new String(txtPass.getPassword());
        String hoten = txtHoten.getText();
        String sdt = txtSdt.getText();
        String role = (String) cbRole.getSelectedItem();
        
        // Validate email
        String emailCheck = validateEmail.checkEmail(email);
        if (!emailCheck.equals("OK")) {
            JOptionPane.showMessageDialog(this,"Lỗi email: ");
            txtTDN.requestFocus();
            return;
        }
        
        // Kiểm tra password có đạt tất cả yêu cầu không
        if (!validateEmail.isPasswordAllValid(password)) {
            JOptionPane.showMessageDialog(this,"Mật khẩu chưa đủ mạnh!");
            txtPass.requestFocus();
            return;
        }
        
        // Validate họ tên
        if (hoten.isEmpty() || hoten.length() < 2) {
            JOptionPane.showMessageDialog(this,"Họ tên phải có ít nhất 2 ký tự");
            txtHoten.requestFocus();
            return;
        }
        
        // Validate số điện thoại
        if (!validate.isInteger(sdt) || !validate.isValidPhoneNumber(sdt)) {
            JOptionPane.showMessageDialog(this,"Số điện thoại phải có 10 chữ số");
            txtSdt.requestFocus();
            return;
        }
        
        try {
            taikhoanDAO dao = new taikhoanDAO();
            
            // Kiểm tra email đã tồn tại
            if (dao.isEmailExists(email)) {
                JOptionPane.showMessageDialog(this,"Email đã tồn tại");
                txtTDN.requestFocus();
                return;
            }
            
            // Tạo đối tượng tài khoản
            taikhoan tk = new taikhoan();
            tk.setEmail(email);
            tk.setPass(password);
            tk.setName(hoten);
            tk.setRole(role);
            tk.setPhone(sdt);
            
            // Đăng ký
            if (dao.register(tk)) {
                JOptionPane.showMessageDialog(this,"Đăng ký thành công!");
                
                // Quay lại form đăng nhập
                closeRegisterDialog();
                
                // Điền email vào ô đăng nhập
                txtDN.setText(email);
                txtMk.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Đăng ký thất bại!" );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDKActionPerformed

    private void lbDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDNMouseClicked
        // TODO add your handling code here:
        closeRegisterDialog();
    }//GEN-LAST:event_lbDNMouseClicked

    private void cbhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhtActionPerformed
        // TODO add your handling code here:
        if (cbht.isSelected()) {
            txtMk.setEchoChar((char) 0); // Hiện mật khẩu
        } else {
            txtMk.setEchoChar('*'); // Ẩn mật khẩu
        }
    }//GEN-LAST:event_cbhtActionPerformed

    private void cbHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHTActionPerformed
        // TODO add your handling code here:
        if (cbHT.isSelected()) {
            txtPass.setEchoChar((char) 0); // Hiện mật khẩu
        } else {
            txtPass.setEchoChar('*'); // Ẩn mật khẩu
        }
    }//GEN-LAST:event_cbHTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dangnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDK;
    private javax.swing.JButton btnDN;
    private javax.swing.JCheckBox cbHT;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JCheckBox cbht;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDK;
    private javax.swing.JLabel lbDN;
    private javax.swing.JLabel lbbl1;
    private javax.swing.JLabel lbbl2;
    private javax.swing.JLabel lbbl3;
    private javax.swing.JLabel lbbl4;
    private javax.swing.JLabel lbbl5;
    private javax.swing.JLabel lbbl6;
    private javax.swing.JTextField txtDN;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JPasswordField txtMk;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTDN;
    // End of variables declaration//GEN-END:variables
}
