/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.loaisanphamDAO;
import DAO.sanphamDAO;
import Models.goiysanpham;
import Models.loaisanpham;
import Models.sanpham;
import database.dbconnection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import servicesANDvalidate.services;
import servicesANDvalidate.validate;

/**
 *
 * @author Admin
 */
public class quanlysanpham extends javax.swing.JPanel {
    private TableRowSorter<DefaultTableModel> sorterSP;
    /**
     * Creates new form quanlysanpham
     */
    public quanlysanpham() throws SQLException {
        initComponents();
        tblloaisp.setModel(new DefaultTableModel(
            new Object[][] {},
            new String [] {"Mã loại", "Tên loại", "Mô tả"}
        ));
        cbloaisp.setSelectedItem(null);
        loadLoaiSP();
        cbloaisp.setEditable(true);
        cbloaiSP();
        tblsanpham.setModel(new DefaultTableModel(
            new Object[][] {},
            new String [] {"Mã sản phẩm", "Tên sản phẩm", "Tên loại sản phẩm", "Số lượng", "Giá bán", "Giá nhập", "Trạng thái"}
        ));
        sorterSP = new TableRowSorter<>((DefaultTableModel) tblsanpham.getModel());
        tblsanpham.setRowSorter(sorterSP);
        txttimkiemsp.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) { filter(); }
        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) { filter(); }
        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) { filter(); }

        private void filter() {
            String text = txttimkiemsp.getText();
            if (text.trim().length() == 0) {
                sorterSP.setRowFilter(null); // hiện tất cả
            } else {
                sorterSP.setRowFilter(RowFilter.regexFilter("(?i)" + text)); 
                // (?i) tìm không phân biệt hoa thường
            }
        }
    });
        loadSP();
    }
    
    private void cbloaiSP() throws SQLException{
        cbloaisp.removeAllItems();
        loaisanphamDAO dao=new loaisanphamDAO(dbconnection.getConnection());
        List<loaisanpham> listcb= dao.getAll();
        for(loaisanpham loai:listcb){
            cbloaisp.addItem(loai);
        }
        AutoCompleteDecorator.decorate(cbloaisp);
    }
    
    private void loadLoaiSP() throws SQLException {
        loaisanphamDAO dao= new loaisanphamDAO(dbconnection.getConnection());
        List<loaisanpham> list=dao.getAll();
        DefaultTableModel model= (DefaultTableModel) tblloaisp.getModel();
        model.setRowCount(0);
        for(loaisanpham loai : list){
            model.addRow(new Object[]{
                loai.getMaloai(),
                loai.getTenloai(),
                loai.getMota()
            });
        }
    }
    
    private void loadSP() throws SQLException {
        sanphamDAO dao= new sanphamDAO(dbconnection.getConnection());
        List<sanpham> list=dao.getAll();
        DefaultTableModel model= (DefaultTableModel) tblsanpham.getModel();
        model.setRowCount(0);
        for(sanpham sp : list){
            model.addRow(new Object[]{
                sp.getMasp(),
                sp.getTensp(),
                sp.getTenloai(),
                sp.getSoluong(),
                sp.getGiaban(),
                sp.getGianhap(),
                sp.getTrangthai()
            });
        }
    }
    
    private void clear() {
        txtmasp.setText("");
        txttensp.setText("");
        txtsoluongton.setText("");
        txtgianhap.setText("");
        txtgiaban.setText("");
        cbloaisp.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmaloai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttenloai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmota = new javax.swing.JTextArea();
        btnthemloai = new javax.swing.JButton();
        btnsualoai = new javax.swing.JButton();
        btnxoaloai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblloaisp = new javax.swing.JTable();
        panelRight = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmasp = new javax.swing.JTextField();
        txttensp = new javax.swing.JTextField();
        txtsoluongton = new javax.swing.JTextField();
        txtgiaban = new javax.swing.JTextField();
        txtgianhap = new javax.swing.JTextField();
        btnthemsp = new javax.swing.JButton();
        btnsuasp = new javax.swing.JButton();
        btnxoasp = new javax.swing.JButton();
        btntimkiemsp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsanpham = new javax.swing.JTable();
        cbloaisp = new javax.swing.JComboBox<>();
        txttimkiemsp = new javax.swing.JTextField();

        panelLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Loại sản phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã loại:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên loại:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mô tả:");

        txtmota.setColumns(20);
        txtmota.setRows(5);
        jScrollPane1.setViewportView(txtmota);

        btnthemloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnthemloai.setText("Thêm");
        btnthemloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemloaiActionPerformed(evt);
            }
        });

        btnsualoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsualoai.setText("Sửa");
        btnsualoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsualoaiActionPerformed(evt);
            }
        });

        btnxoaloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnxoaloai.setText("Xóa");
        btnxoaloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaloaiActionPerformed(evt);
            }
        });

        tblloaisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã loại", "Tên loại", "Mô tả"
            }
        ));
        tblloaisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblloaispMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblloaisp);

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnthemloai)
                        .addGap(34, 34, 34)
                        .addComponent(btnsualoai)
                        .addGap(34, 34, 34)
                        .addComponent(btnxoaloai))
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelLeftLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttenloai))
                                .addGroup(panelLeftLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLeftLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttenloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemloai)
                    .addComponent(btnsualoai)
                    .addComponent(btnxoaloai))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Sản phẩm");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mã sản phẩm:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tên sản phẩm:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tên loại:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Số lượng:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Giá bán:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Giá nhập:");

        txttensp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenspActionPerformed(evt);
            }
        });

        txtgianhap.setMaximumSize(new java.awt.Dimension(64, 22));

        btnthemsp.setText("Thêm");
        btnthemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemspActionPerformed(evt);
            }
        });

        btnsuasp.setText("Sửa");
        btnsuasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaspActionPerformed(evt);
            }
        });

        btnxoasp.setText("Xóa");
        btnxoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaspActionPerformed(evt);
            }
        });

        btntimkiemsp.setText("Tìm kiếm:");
        btntimkiemsp.setToolTipText("");

        tblsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Số lượng", "Giá bán", "Giá nhập", "Trạng thái"
            }
        ));
        tblsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsanphamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblsanpham);

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRightLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnthemsp)
                                .addGap(53, 53, 53)
                                .addComponent(btnsuasp)
                                .addGap(59, 59, 59)
                                .addComponent(btnxoasp)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelRightLayout.createSequentialGroup()
                                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelRightLayout.createSequentialGroup()
                                        .addComponent(btntimkiemsp)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttimkiemsp))
                                    .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRightLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtgianhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(panelRightLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsoluongton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoluongton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntimkiemsp)
                    .addComponent(txttimkiemsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemsp)
                    .addComponent(btnsuasp)
                    .addComponent(btnxoasp))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemloaiActionPerformed
        String maloai = txtmaloai.getText();
        String tenloai = txttenloai.getText();
        String mota =txtmota.getText();
        StringBuilder errors = new StringBuilder();
        if (validate.isEmpty(maloai)) {
            errors.append("- Mã loại sản phẩm không được để trống.\n");
        } else if (!validate.isInteger(maloai)) {
            errors.append("- Mã loại sản phẩm phải là số nguyên.\n");
        } else if (!validate.isPositiveInteger(maloai)) {
            errors.append("- Mã loại sản phẩm phải là số nguyên dương.\n");
        }
        if (validate.isEmpty(tenloai)){
            errors.append("- Tên loại sản phẩm không được để trống.\n");
        }
        
        int Maloai=Integer.parseInt(maloai);
        loaisanpham loaisp= new loaisanpham();
        loaisp.setMaloai(Maloai);
        loaisp.setTenloai(tenloai);
        loaisp.setMota(mota);
        loaisanphamDAO loaiDAO=new loaisanphamDAO(dbconnection.getConnection());
        try{
            if(loaiDAO.isMaLoai(Maloai)){
                JOptionPane.showMessageDialog(this, "Mã phiếu đã tồn tại trong cơ sở dữ liệu!");
                return;
            }
            else{
                loaiDAO.insert(loaisp);
                JOptionPane.showMessageDialog(this, "thêm loại sản phẩm thành công");
                loadLoaiSP();
                txtmaloai.setText(null);
                txttenloai.setText(null);
                txtmota.setText(null);
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnthemloaiActionPerformed

    private void btnsualoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsualoaiActionPerformed
        int row=tblloaisp.getSelectedRow();
        String maloai=txtmaloai.getText().trim();
        String tenloai=txttenloai.getText().trim();
        String mota=txtmota.getText().trim();
        
        if (maloai.isEmpty() || tenloai.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống mã loại và tên loại!");
            return;
        }
            if(row == -1){
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 loại sản phẩm để xem");
            return;
        }
        else{
            try{
                loaisanpham sp=new loaisanpham();
                sp.setMaloai(Integer.parseInt(maloai));
                sp.setTenloai(tenloai);
                sp.setMota(mota);
                
                loaisanphamDAO dao=new loaisanphamDAO(dbconnection.getConnection());
                boolean ok=dao.update(sp);
                if(ok){
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    loadLoaiSP();
                    txtmaloai.setText(null);
                    txttenloai.setText(null);
                    txtmota.setText(null);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnsualoaiActionPerformed

    private void tblloaispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblloaispMouseClicked
        int row= tblloaisp.getSelectedRow();
        if(row>=0){
            txtmaloai.setText(tblloaisp.getValueAt(row, 0).toString());
            txttenloai.setText(tblloaisp.getValueAt(row, 1).toString());
            txtmota.setText(tblloaisp.getValueAt(row, 2).toString());  
        }
        txtmaloai.setEnabled(false);
    }//GEN-LAST:event_tblloaispMouseClicked

    private void btnxoaloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaloaiActionPerformed
        int[] selectedRows= tblloaisp.getSelectedRows();
        if(selectedRows.length==0){
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 loại sản phẩm để xóa");
            return;
        }
        List<Integer> listmaloai= new ArrayList<>();
        for(int row : selectedRows){
            int maloai=(int) tblloaisp.getValueAt(row, 0);
            listmaloai.add(maloai);
        }
        try{
            loaisanphamDAO loaidao=new loaisanphamDAO(dbconnection.getConnection());
            boolean ok=loaidao.xoaNhieuLoaiSanPham(listmaloai);
            if(ok){
                JOptionPane.showMessageDialog(this, "Xóa loại sản phẩm thành công");
            }
            else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi xóa loại sản phẩm: " + e.getMessage());
            e.printStackTrace();
        }
        try {
            loadLoaiSP();
        } catch (SQLException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnxoaloaiActionPerformed

    private void txttenspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenspActionPerformed

    private void btnthemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemspActionPerformed
        String masptext=txtmasp.getText();
        String tensptext=txttensp.getText();
        loaisanpham loaisp= (loaisanpham) cbloaisp.getSelectedItem();
        String soluongtext=txtsoluongton.getText();
        String giabantext=txtgiaban.getText();
        String gianhaptext=txtgianhap.getText();
        if (validate.isEmpty(masptext) || !validate.isPositiveInteger(masptext)) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm phải là số nguyên dương!");
            return;
        }
        else if (validate.isEmpty(tensptext)) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống!");
            return ;
        }
        else if (loaisp == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại sản phẩm!");
            return;
        }
        else if (validate.isEmpty(soluongtext) || !validate.isInteger(soluongtext)) {
            JOptionPane.showMessageDialog(this, "Số lượng tồn phải là số nguyên!");
            return;
        }
        else if (Integer.parseInt(soluongtext) < 0) {
            JOptionPane.showMessageDialog(this, "Số lượng tồn phải >= 0!");
            return;
        }
        else if (validate.isEmpty(giabantext)) {
            JOptionPane.showMessageDialog(this, "Giá bán không được để trống!");
            return;
        }
        try {
            double giaban = Double.parseDouble(giabantext);
            if (giaban < 0) {
                JOptionPane.showMessageDialog(this, "Giá bán phải >= 0!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá bán phải là số hợp lệ!");
            return;
        }
        if (validate.isEmpty(gianhaptext)) {
            JOptionPane.showMessageDialog(this, "Giá nhập không được để trống!");
            return;
        }
        try {
            double gianhap = Double.parseDouble(gianhaptext);
            if (gianhap < 0) {
                JOptionPane.showMessageDialog(this, "Giá nhập phải >= 0!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá nhập phải là số hợp lệ!");
            return;
        }
        if (Double.parseDouble(giabantext) < Double.parseDouble(gianhaptext)) {
            JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn hoặc bằng giá nhập!");
            return;
        }
        int masp = Integer.parseInt(masptext);
        int soluong = Integer.parseInt(soluongtext);
        
        int maloai=loaisp.getMaloai();
        double gianhap = Double.parseDouble(gianhaptext);
        double giaban = Double.parseDouble(giabantext);
        String tensp = tensptext;

        sanpham sp=new sanpham();
        sp.setMasp(masp);
        sp.setTensp(tensp);
        sp.setMaloai(maloai);
        sp.setSoluong(soluong);
        sp.setGianhap(gianhap);
        sp.setGiaban((float) giaban);

        sanphamDAO dao = new sanphamDAO(dbconnection.getConnection());
        if (dao.isMaspExist(masp)) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại!");
            return;
        }
        boolean success;
        try {
            success = dao.insert(sp);
            if (success) {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(quanlysanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
        try {
            loadSP();
        } catch (SQLException ex) {
            Logger.getLogger(quanlysanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnthemspActionPerformed

    private void tblsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsanphamMouseClicked
        int selectedRow = tblsanpham.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy dữ liệu từ table
            int masp = Integer.parseInt(tblsanpham.getValueAt(selectedRow, 0).toString());
            String tensp = tblsanpham.getValueAt(selectedRow, 1).toString();
            String tenloai = tblsanpham.getValueAt(selectedRow, 2).toString();
            int soluong = Integer.parseInt(tblsanpham.getValueAt(selectedRow, 3).toString());
            double gianhap = Double.parseDouble(tblsanpham.getValueAt(selectedRow, 4).toString());
            double giaban = Double.parseDouble(tblsanpham.getValueAt(selectedRow, 5).toString());

            // Set dữ liệu vào form
            txtmasp.setText(String.valueOf(masp));
            txttensp.setText(tensp);
            txtsoluongton.setText(String.valueOf(soluong));
            txtgianhap.setText(String.valueOf(gianhap));
            txtgiaban.setText(String.valueOf(giaban));

            // Set combobox loại sản phẩm
            for (int i = 0; i < cbloaisp.getItemCount(); i++) {
                loaisanpham item = (loaisanpham) cbloaisp.getItemAt(i);
                if (item.getTenloai().equals(tenloai)) {
                    cbloaisp.setSelectedIndex(i);
                    break;
                }
            }
            txtmasp.setEditable(false);
        }
    }//GEN-LAST:event_tblsanphamMouseClicked

    private void btnsuaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaspActionPerformed
        try {
            int masp = Integer.parseInt(txtmasp.getText());
            String tensp = txttensp.getText();
            int soluong = Integer.parseInt(txtsoluongton.getText());
            double gianhap = Double.parseDouble(txtgianhap.getText());
            double giaban = Double.parseDouble(txtgiaban.getText());

            loaisanpham loaisp = (loaisanpham) cbloaisp.getSelectedItem();
            if (loaisp == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn loại sản phẩm!");
                return;
            }
            int maloai = loaisp.getMaloai();
            sanpham sp=new sanpham();
            sp.setMasp(masp);
            sp.setTensp(tensp);
            sp.setMaloai(maloai);
            sp.setSoluong(soluong);
            sp.setGiaban(giaban);
            sp.setGianhap(gianhap);
            
            sanphamDAO dao= new sanphamDAO(dbconnection.getConnection());
            try {
                if(dao.update(sp)){
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                    loadSP();
                    clear();  
                } 
                else{
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(quanlysanpham.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nhập sai định dạng số!");
        }
    }//GEN-LAST:event_btnsuaspActionPerformed

    private void btnxoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaspActionPerformed
        int[] selectedRows= tblsanpham.getSelectedRows();
        if(selectedRows.length==0){
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 sản phẩm để xóa");
            return;
        }
        List<Integer> listmasp= new ArrayList<>();
        for(int row : selectedRows){
            int masp=(int) tblsanpham.getValueAt(row, 0);
            listmasp.add(masp);
        }
        try{
            sanphamDAO spdao=new sanphamDAO(dbconnection.getConnection());
            boolean ok=spdao.xoaNhieuSanPham(listmasp);
            if(ok){
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công");
                loadSP();
            }
            else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi xóa sản phẩm: " + e.getMessage());
            e.printStackTrace();
        }
        try {
            loadLoaiSP();
        } catch (SQLException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnxoaspActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsualoai;
    private javax.swing.JButton btnsuasp;
    private javax.swing.JButton btnthemloai;
    private javax.swing.JButton btnthemsp;
    private javax.swing.JButton btntimkiemsp;
    private javax.swing.JButton btnxoaloai;
    private javax.swing.JButton btnxoasp;
    private javax.swing.JComboBox<loaisanpham> cbloaisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JTable tblloaisp;
    private javax.swing.JTable tblsanpham;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtgianhap;
    private javax.swing.JTextField txtmaloai;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextArea txtmota;
    private javax.swing.JTextField txtsoluongton;
    private javax.swing.JTextField txttenloai;
    private javax.swing.JTextField txttensp;
    private javax.swing.JTextField txttimkiemsp;
    // End of variables declaration//GEN-END:variables
}
