/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.loaisanphamDAO;
import Models.loaisanpham;
import database.dbconnection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicesANDvalidate.services;
import servicesANDvalidate.validate;

/**
 *
 * @author Admin
 */
public class quanlysanpham extends javax.swing.JPanel {

    /**
     * Creates new form quanlysanpham
     */
    public quanlysanpham() throws SQLException {
        initComponents();
        tblloaisp.setModel(new DefaultTableModel(
            new Object[][] {},
            new String [] {"Mã loại", "Tên loại", "Mô tả"}
        ));
        loadLoaiSP();
        
    }
    
    private void loadLoaiSP() throws SQLException {
        loaisanphamDAO dao= new loaisanphamDAO(dbconnection.getConnection());
        List<loaisanpham> list=dao.getAll();
        DefaultTableModel model= (DefaultTableModel) tblloaisp.getModel();
        model.setRowCount(0);
        for(loaisanpham loai : list){
            model.addRow(new Object[]{
                loai.getMaloai(),
                loai.getTenloai(),
                loai.getMota()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmaloai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttenloai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmota = new javax.swing.JTextArea();
        btnthemloai = new javax.swing.JButton();
        btnsualoai = new javax.swing.JButton();
        btnxoaloai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblloaisp = new javax.swing.JTable();
        panelRight = new javax.swing.JPanel();

        panelLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Loại sản phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã loại:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên loại:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mô tả:");

        txtmota.setColumns(20);
        txtmota.setRows(5);
        jScrollPane1.setViewportView(txtmota);

        btnthemloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnthemloai.setText("Thêm");
        btnthemloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemloaiActionPerformed(evt);
            }
        });

        btnsualoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsualoai.setText("Sửa");
        btnsualoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsualoaiActionPerformed(evt);
            }
        });

        btnxoaloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnxoaloai.setText("Xóa");
        btnxoaloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaloaiActionPerformed(evt);
            }
        });

        tblloaisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã loại", "Tên loại", "Mô tả"
            }
        ));
        tblloaisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblloaispMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblloaisp);

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnthemloai)
                        .addGap(34, 34, 34)
                        .addComponent(btnsualoai)
                        .addGap(34, 34, 34)
                        .addComponent(btnxoaloai))
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelLeftLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttenloai))
                                .addGroup(panelLeftLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLeftLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttenloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemloai)
                    .addComponent(btnsualoai)
                    .addComponent(btnxoaloai))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        panelRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemloaiActionPerformed
        String maloai = txtmaloai.getText();
        String tenloai = txttenloai.getText();
        String mota =txtmota.getText();
        StringBuilder errors = new StringBuilder();
        if (validate.isEmpty(maloai)) {
            errors.append("- Mã loại sản phẩm không được để trống.\n");
        } else if (!validate.isInteger(maloai)) {
            errors.append("- Mã loại sản phẩm phải là số nguyên.\n");
        } else if (!validate.isPositiveInteger(maloai)) {
            errors.append("- Mã loại sản phẩm phải là số nguyên dương.\n");
        }
        if (validate.isEmpty(tenloai)){
            errors.append("- Tên loại sản phẩm không được để trống.\n");
        }
        
        int Maloai=Integer.parseInt(maloai);
        loaisanpham loaisp= new loaisanpham();
        loaisp.setMaloai(Maloai);
        loaisp.setTenloai(tenloai);
        loaisp.setMota(mota);
        loaisanphamDAO loaiDAO=new loaisanphamDAO(dbconnection.getConnection());
        try{
            if(loaiDAO.isMaLoai(Maloai)){
                JOptionPane.showMessageDialog(this, "Mã phiếu đã tồn tại trong cơ sở dữ liệu!");
                return;
            }
            else{
                loaiDAO.insert(loaisp);
                JOptionPane.showMessageDialog(this, "thêm loại sản phẩm thành công");
                loadLoaiSP();
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnthemloaiActionPerformed

    private void btnsualoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsualoaiActionPerformed
        int row=tblloaisp.getSelectedRow();
        String maloai=txtmaloai.getText().trim();
        String tenloai=txttenloai.getText().trim();
        String mota=txtmota.getText().trim();
        
        if (maloai.isEmpty() || tenloai.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống mã loại và tên loại!");
            return;
        }
            if(row == -1){
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 loại sản phẩm để xem");
            return;
        }
        else{
            try{
                loaisanpham sp=new loaisanpham();
                sp.setMaloai(Integer.parseInt(maloai));
                sp.setTenloai(tenloai);
                sp.setMota(mota);
                
                loaisanphamDAO dao=new loaisanphamDAO(dbconnection.getConnection());
                boolean ok=dao.update(sp);
                if(ok){
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    loadLoaiSP();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnsualoaiActionPerformed

    private void tblloaispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblloaispMouseClicked
        int row= tblloaisp.getSelectedRow();
        if(row>=0){
            txtmaloai.setText(tblloaisp.getValueAt(row, 0).toString());
            txttenloai.setText(tblloaisp.getValueAt(row, 1).toString());
            txtmota.setText(tblloaisp.getValueAt(row, 2).toString());  
        }
        txtmaloai.setEnabled(false);
    }//GEN-LAST:event_tblloaispMouseClicked

    private void btnxoaloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaloaiActionPerformed
        int[] selectedRows= tblloaisp.getSelectedRows();
        if(selectedRows.length==0){
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 loại sản phẩm để xóa");
            return;
        }
        List<Integer> listmaloai= new ArrayList<>();
        for(int row : selectedRows){
            int maloai=(int) tblloaisp.getValueAt(row, 0);
            listmaloai.add(maloai);
        }
        try{
            loaisanphamDAO loaidao=new loaisanphamDAO(dbconnection.getConnection());
            boolean ok=loaidao.xoaNhieuLoaiSanPham(listmaloai);
            if(ok){
                JOptionPane.showMessageDialog(this, "Xóa loại sản phẩm thành công");
            }
            else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi xóa loại sản phẩm: " + e.getMessage());
            e.printStackTrace();
        }
        try {
            loadLoaiSP();
        } catch (SQLException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnxoaloaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsualoai;
    private javax.swing.JButton btnthemloai;
    private javax.swing.JButton btnxoaloai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JTable tblloaisp;
    private javax.swing.JTextField txtmaloai;
    private javax.swing.JTextArea txtmota;
    private javax.swing.JTextField txttenloai;
    // End of variables declaration//GEN-END:variables
}
