/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.donvivanchuyenDAO;
import Models.donvivanchuyen;
import database.dbconnection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import servicesANDvalidate.validate;

/**
 *
 * @author Admin
 */
public class quanlydonvivanchuyen extends javax.swing.JPanel {
    private TableRowSorter<DefaultTableModel> sorterDVVC;
    /**
     * Creates new form quanlydonvivanchuyen
     */
    public quanlydonvivanchuyen() throws SQLException{
        initComponents();
        loadDvvc();
        sorterDVVC = new TableRowSorter<>((DefaultTableModel) tbldvvc.getModel());
        tbldvvc.setRowSorter(sorterDVVC);

        txttimkiemdvvc.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filter(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filter(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filter(); }

            private void filter() {
                String text = txttimkiemdvvc.getText();
                if (text.trim().length() == 0) {
                    sorterDVVC.setRowFilter(null);
                } else {
                    sorterDVVC.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
        });  
    }
    
    private void clearform(){
        txtmadonvi.setText("");
        txttendonvi.setText("");
        txtdiachidonvi.setText("");
        txtsdtdonvi.setText("");
    }
    
    private void loadDvvc() throws SQLException{
        donvivanchuyenDAO dao = new donvivanchuyenDAO(dbconnection.getConnection());
        List<donvivanchuyen> listncc = dao.getAll();
        DefaultTableModel model = (DefaultTableModel) tbldvvc.getModel();
        model.setRowCount(0);
        for (donvivanchuyen x : listncc) {
            model.addRow(new Object[]{
                x.getMadvvc(),
                x.getTendvvc(),
                x.getSdtdvvc(),
                x.getDiachidvvc()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        txtmadonvi = new javax.swing.JTextField();
        txttendonvi = new javax.swing.JTextField();
        txtdiachidonvi = new javax.swing.JTextField();
        txtsdtdonvi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldvvc = new javax.swing.JTable();
        btnthemdonvi = new javax.swing.JButton();
        btnsuadonvi = new javax.swing.JButton();
        btnxoadonvi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txttimkiemdvvc = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐƠN VỊ VẬN CHUYỂN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã đơn vị:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên đơn vị:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label.setText(" Địa chỉ:");

        txtmadonvi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txttendonvi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtdiachidonvi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtsdtdonvi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsdtdonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtdonviActionPerformed(evt);
            }
        });

        tbldvvc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "mã đơn vị vận chuyển", "tên đơn vị ", "số điện thoại", "địa chỉ"
            }
        ));
        tbldvvc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldvvcMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldvvc);

        btnthemdonvi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnthemdonvi.setText("Thêm");
        btnthemdonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemdonviActionPerformed(evt);
            }
        });

        btnsuadonvi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsuadonvi.setText("Sửa");
        btnsuadonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuadonviActionPerformed(evt);
            }
        });

        btnxoadonvi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnxoadonvi.setText("Xóa");
        btnxoadonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoadonviActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tìm kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtdiachidonvi, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                            .addComponent(txtmadonvi))
                                        .addGap(121, 121, 121)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(label))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsdtdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttendonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnthemdonvi)
                                        .addGap(58, 58, 58)
                                        .addComponent(btnsuadonvi)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnxoadonvi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttimkiemdvvc)))))
                        .addGap(0, 304, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmadonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttendonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label)
                    .addComponent(txtdiachidonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsdtdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemdonvi)
                    .addComponent(btnsuadonvi)
                    .addComponent(btnxoadonvi))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttimkiemdvvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsdtdonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtdonviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtdonviActionPerformed

    private void btnthemdonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemdonviActionPerformed
        String ma = txtmadonvi.getText().trim();
        String ten = txttendonvi.getText().trim();
        String sdt = txtdiachidonvi.getText().trim();
        String diachi = txtsdtdonvi.getText().trim();
        if (validate.isEmpty(ma)) {
            JOptionPane.showMessageDialog(this, "Mã đơn vị không được để trống!");
            return;
        }
        if (!validate.isPositiveInteger(ma)) {
            JOptionPane.showMessageDialog(this, "Mã đơn vị phải là số nguyên dương!");
            return;
        }
        int madvvc = Integer.parseInt(ma);
        if (validate.isEmpty(ten)) {
            JOptionPane.showMessageDialog(this, "Tên đơn vị không được để trống!");
            return;
        }
        if (!validate.isValidPhoneNumber(sdt)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ (9-11 số)!");
            return;
        }
        if (validate.isEmpty(diachi)) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống!");
            return;
        }
        try {
            donvivanchuyenDAO dao = new donvivanchuyenDAO(dbconnection.getConnection());
            if (dao.exists(madvvc)) {
                JOptionPane.showMessageDialog(this, "Mã đơn vị đã tồn tại!");
                return;
            }
            donvivanchuyen dv = new donvivanchuyen();
            dv.setMadvvc(madvvc);
            dv.setTendvvc(ten);
            dv.setSdtdvvc(sdt);
            dv.setDiachidvvc(diachi);

            // Thêm
            if (dao.insert(dv)) {
                JOptionPane.showMessageDialog(this, "Thêm đơn vị vận chuyển thành công!");
                loadDvvc();
                clearform();

            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnthemdonviActionPerformed

    private void btnsuadonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuadonviActionPerformed
        int row = tbldvvc.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng để sửa");
            return;
        }
        String maStr = txtmadonvi.getText().trim();
        String ten = txttendonvi.getText().trim();
        String sdt = txtdiachidonvi.getText().trim();
        String diachi = txtsdtdonvi.getText().trim();
        if (maStr.isEmpty() || ten.isEmpty() || sdt.isEmpty() || diachi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống!");
            return;
        }
        int madvvc;
        try {
            madvvc = Integer.parseInt(maStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã đơn vị phải là phải là số!");
            return;
        }

        donvivanchuyen dv = new donvivanchuyen(madvvc, ten, sdt, diachi);
        donvivanchuyenDAO dao=new donvivanchuyenDAO(dbconnection.getConnection());
        try {
            if (dao.update(dv)) {
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                loadDvvc();
                clearform();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại!");
                clearform();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa!");
        }
    }//GEN-LAST:event_btnsuadonviActionPerformed

    private void tbldvvcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldvvcMouseClicked
        int row = tbldvvc.getSelectedRow();
        if (row>=0) {
            txtmadonvi.setText(tbldvvc.getValueAt(row, 0).toString());
            txttendonvi.setText(tbldvvc.getValueAt(row, 1).toString());
            txtsdtdonvi.setText(tbldvvc.getValueAt(row, 3).toString());
            txtdiachidonvi.setText(tbldvvc.getValueAt(row, 2).toString());
        }
    }//GEN-LAST:event_tbldvvcMouseClicked

    private void btnxoadonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoadonviActionPerformed
        int[] selectedRows = tbldvvc.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Hãy chọn ít nhất 1 đơn vị vận chuyển để xóa");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa đơn vị vận chuyển không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tbldvvc.getModel();
        List<Integer> listMaDVVC = new ArrayList<>();
        for (int i : selectedRows) {
            int ma = Integer.parseInt(model.getValueAt(i, 0).toString());
            listMaDVVC.add(ma);
        }
        donvivanchuyenDAO dao= new donvivanchuyenDAO(dbconnection.getConnection());
        for (int ma : listMaDVVC) {
        try {
                dao.delete(ma);
                loadDvvc();
                clearform();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Không thể xóa nhà cung cấp có mã: " + ma);
            }
        }
        clearform();
    }//GEN-LAST:event_btnxoadonviActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsuadonvi;
    private javax.swing.JButton btnthemdonvi;
    private javax.swing.JButton btnxoadonvi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable tbldvvc;
    private javax.swing.JTextField txtdiachidonvi;
    private javax.swing.JTextField txtmadonvi;
    private javax.swing.JTextField txtsdtdonvi;
    private javax.swing.JTextField txttendonvi;
    private javax.swing.JTextField txttimkiemdvvc;
    // End of variables declaration//GEN-END:variables
}
