/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.nhacungcapDAO;
import Models.nhacungcap;
import database.dbconnection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import servicesANDvalidate.validate;

/**
 *
 * @author Admin
 */
public class quanlynhacungcap extends javax.swing.JPanel {
    private TableRowSorter<DefaultTableModel> sorterNCC;
    /**
     * Creates new form quanlynhacungcap
     */
    public quanlynhacungcap() throws SQLException {
        initComponents();
        loadNhaCungCap();
        sorterNCC = new TableRowSorter<>((DefaultTableModel) tblnhacc.getModel());
        tblnhacc.setRowSorter(sorterNCC);

        txttimkiemncc.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filter(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filter(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filter(); }

            private void filter() {
                String text = txttimkiemncc.getText();
                if (text.trim().length() == 0) {
                    sorterNCC.setRowFilter(null);
                } else {
                    sorterNCC.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
        });  
    }

    private void clear() {
        txtmancc.setText("");
        txttenncc.setText("");
        txtdiachincc.setText("");
        txtsdtncc.setText("");
        txttimkiemncc.setText("");
    }
    private void loadNhaCungCap() throws SQLException {
        nhacungcapDAO dao = new nhacungcapDAO(dbconnection.getConnection());
        List<nhacungcap> listncc = dao.getAll();
        DefaultTableModel model = (DefaultTableModel) tblnhacc.getModel();
        model.setRowCount(0);
        for (nhacungcap x : listncc) {
            model.addRow(new Object[]{
                x.getMancc(),
                x.getTenncc(),
                x.getDiachincc(),
                x.getSdtncc()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmancc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttenncc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdiachincc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtsdtncc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttimkiemncc = new javax.swing.JTextField();
        btnthemncc = new javax.swing.JButton();
        btnsuancc = new javax.swing.JButton();
        btnxoancc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhacc = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÀ CUNG CẤP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhà cung cấp:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên nhà cung cấp:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Địa chỉ:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số điện thoại:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tìm kiếm:");

        btnthemncc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnthemncc.setText("Thêm");
        btnthemncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemnccActionPerformed(evt);
            }
        });

        btnsuancc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsuancc.setText("Sửa");
        btnsuancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuanccActionPerformed(evt);
            }
        });

        btnxoancc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnxoancc.setText("Xóa");
        btnxoancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoanccActionPerformed(evt);
            }
        });

        tblnhacc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại"
            }
        ));
        tblnhacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnhaccMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblnhacc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthemncc)
                        .addGap(50, 50, 50)
                        .addComponent(btnsuancc)
                        .addGap(57, 57, 57)
                        .addComponent(btnxoancc))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttimkiemncc))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmancc))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdiachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsdtncc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttenncc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txttenncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdiachincc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtsdtncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttimkiemncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemncc)
                    .addComponent(btnsuancc)
                    .addComponent(btnxoancc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemnccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemnccActionPerformed
        String ma = txtmancc.getText().trim();
        String ten = txttenncc.getText().trim();
        String diachi = txtdiachincc.getText().trim();
        String sdt = txtsdtncc.getText().trim();

        if (validate.isEmpty(ma) || validate.isEmpty(ten)
                || validate.isEmpty(diachi) || validate.isEmpty(sdt)) {
            JOptionPane.showMessageDialog(this, "Không được để trống bất kỳ trường nào!");
            return;
        }
        if (!validate.isPositiveInteger(ma)) {
            JOptionPane.showMessageDialog(this, "Mã nhà cung cấp phải là số nguyên dương!");
            return;
        }
        if (!validate.isValidPhoneNumber(sdt)) {
            JOptionPane.showMessageDialog(this, "nhập đúng định dạng của số điện thoại");
            return;
        }
        nhacungcap ncc = new nhacungcap();
        ncc.setMancc(Integer.parseInt(ma));
        ncc.setTenncc(ten);
        ncc.setDiachincc(diachi);
        ncc.setSdtncc(sdt);
        try {
            nhacungcapDAO dao = new nhacungcapDAO(dbconnection.getConnection());
            if (dao.findById(ncc.getMancc()) != null) {
                JOptionPane.showMessageDialog(this, "Mã nhà cung cấp đã tồn tại!");
                return;
            }
            boolean success = dao.insert(ncc);
            if (success) {
                JOptionPane.showMessageDialog(this, "Thêm nhà cung cấp thành công!");
                loadNhaCungCap();
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi SQL: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnthemnccActionPerformed

    private void btnsuanccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuanccActionPerformed
        String ma = txtmancc.getText().trim();
        String ten = txttenncc.getText().trim();
        String diachi = txtdiachincc.getText().trim();
        String sdt = txtsdtncc.getText().trim();
        int selectedRow = tblnhacc.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 nhà cung cấp để sửa");
            return;
        }
        if (validate.isEmpty(ma) || validate.isEmpty(ten) || 
            validate.isEmpty(diachi) || validate.isEmpty(sdt)) {
            JOptionPane.showMessageDialog(this, "Không được để trống trường nào!");
            return;
        }
        if (!validate.isPositiveInteger(ma)) {
            JOptionPane.showMessageDialog(this, "Mã nhà cung cấp phải là số nguyên dương!");
            return;
        }
        if (validate.isValidPhoneNumber(sdt)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ (9–11 số)!");
            return;
        }
        if (!ten.matches("[\\p{L}\\s]+")) {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp không được chứa số hoặc ký tự đặc biệt!");
            return;
        }

        try {
            nhacungcapDAO dao = new nhacungcapDAO(dbconnection.getConnection());
           
            nhacungcap ncc = new nhacungcap();
            ncc.setMancc(Integer.parseInt(ma));
            ncc.setTenncc(ten);
            ncc.setDiachincc(diachi);
            ncc.setSdtncc(sdt);

            boolean success = dao.update(ncc);

            if (success) {
                JOptionPane.showMessageDialog(this, "Cập nhật nhà cung cấp thành công!");
                loadNhaCungCap();
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi SQL: " + e.getMessage());
        }
    }//GEN-LAST:event_btnsuanccActionPerformed

    private void tblnhaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnhaccMouseClicked
        int row = tblnhacc.getSelectedRow();
        if (row>=0) {
            txtmancc.setText(tblnhacc.getValueAt(row, 0).toString());
            txttenncc.setText(tblnhacc.getValueAt(row, 1).toString());
            txtdiachincc.setText(tblnhacc.getValueAt(row, 2).toString());
            txtsdtncc.setText(tblnhacc.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_tblnhaccMouseClicked

    private void btnxoanccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoanccActionPerformed
        int[] selectedRows = tblnhacc.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Hãy chọn ít nhất 1 nhà cung cấp để xóa");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa nhà cung cấp không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblnhacc.getModel();
        List<Integer> listMaNCC = new ArrayList<>();
        for (int i : selectedRows) {
            int ma = Integer.parseInt(model.getValueAt(i, 0).toString());
            listMaNCC.add(ma);
        }
        nhacungcapDAO dao= new nhacungcapDAO(dbconnection.getConnection());
        for (int ma : listMaNCC) {
        try {
                dao.delete(ma);
                loadNhaCungCap();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Không thể xóa nhà cung cấp có mã: " + ma);
            }
        }
        clear();
    }//GEN-LAST:event_btnxoanccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsuancc;
    private javax.swing.JButton btnthemncc;
    private javax.swing.JButton btnxoancc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblnhacc;
    private javax.swing.JTextField txtdiachincc;
    private javax.swing.JTextField txtmancc;
    private javax.swing.JTextField txtsdtncc;
    private javax.swing.JTextField txttenncc;
    private javax.swing.JTextField txttimkiemncc;
    // End of variables declaration//GEN-END:variables
}
